Update build_and_push_docker_to_cloud.yml

diff --git a/.github/workflows/build_and_push_docker_to_cloud.yml b/.github/workflows/build_and_push_docker_to_cloud.yml
--- a/.github/workflows/build_and_push_docker_to_cloud.yml
+++ b/.github/workflows/build_and_push_docker_to_cloud.yml
@@ -1,4 +1,4 @@
-name: Build & push Docker image to GCP
+name: Build & push Docker image to cloud provider
 on:
   workflow_dispatch:
     inputs:
@@ -6,6 +6,9 @@ on:
         description: "The name you want to give the Docker image built"
         required: false
         default: "my-cool-docker-image"
+      CloudProvider:
+        description: "The cloud provider you want to push the Docker image to [AWS or GCP]"
+        required: true
 
 jobs:
   build-and-push-image:
@@ -13,6 +16,12 @@ jobs:
     environment: gcp
 
     steps:
+      - name: Validate input
+        if: ${{ github.event.inputs.CloudProvider }} != "AWS" || ${{ github.event.inputs.CloudProvider }} != "GCP"
+        run: |
+          echo "Error! Please choose either AWS or GCP as the cloud provider."
+          exit 1
+        
       - name: Check out code
         uses: actions/checkout@v2
 
